language: java

jdk:
  - oraclejdk7
  
before_script:
  - sh get-idea-ic.sh
  - sed -i -- "s/{{PLUGIN_VERSION}}/$TRAVIS_TAG/g" META-INF/plugin.xml

script:
  - ant all
  - mv TestFairyAndroidStudioPlugin.zip testfairy-intellij-$TRAVIS_TAG-bin.zip
  
deploy:
  provider: releases
  api_key:
    secure: Z8gzTqeAOynwWAWcaSvh8Q6LG9O8ch5TQCPro0ioVyVUfkVV5Ud17uLMknbgGMb9zRuZ7hV2Jr8oSoONCYSrtzak+WCrfXrx75K6cqH02Uw2JSRjFePRiVNNMF0ap+fPX/hH+693wiBH0ziS9ZAw0zf4HOXKH6Uej8j6Axjrh8pmKRbgDOYaFQGKrUM/KixZyXrT4jn+URuRehjyIOyYHdf9jDlMPQGsQtGSE6/Vfwf4xfKLnOdQSjJhjKpO/OKtu91Q4eGLcY5JhWO8GQUSqsLUut9OZkmh3fFXwbcLb5U/8n2SDQYzjy25y3O9dn77D48GCvpk2TTt0zDVw1FHJbdKJt6r3xPYYzcaCCtQq5Z5nGXhZgxSxtBR3iIIKMA5LhsD0MfTZpkIVrGm4WaDTYftXvwFc9t2u1YHNi/yWCo8S5hndeKQrWu1fdCGXoIm8l5QHC9KE3UrNLW0kArZjzPVbGEEEaoGsJvHibnGviAsFRYVJhZpEvldrUN1qTzOXO0ncv4twm+CfLxK6xqE8bHp8mDldKWVQHq9bzFZO0hdKmzo47WchwH8mNNWqYQNEJmBaz+UiukKXJzaRKFsGqfkQZ+bi8AiakuZmHtWfQWd0OXTZ/6aAhxiLbazkAeli9SCIa40sEw8Pn+KDB2uM29pIs09xEaaBwnuO5gsJ0s=
  file: testfairy-intellij-$TRAVIS_TAG-bin.zip
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
