language: java
jdk:
  - oraclejdk7

before_script:
  - sh get-idea-ic.sh
  - sed -i -- "s/{{PLUGIN_VERSION}}/$TRAVIS_TAG/g" META-INF/plugin.xml

script:
  - echo $JAVA_HOME
  - find $JAVA_HOME
  - find /usr -name "java-7-oracle"
  - ant all
  - mv TestFairyAndroidStudioPlugin.zip testfairy-intellij-$TRAVIS_TAG-bin.zip

deploy:
  provider: releases
  api_key:
    secure: ypOLA2XUBVZZhEa5xSEbkn2+Qa9pOGVHVKuouE/Znq0NVgrN753j2hTe5nReR4/VF1wzKVOTrjS+8sS7O90sX4Imwlu/ZEf6coD91zN1FGJI7/JiZcy/Zo1PHMJe1Ia/yFhKPQu52X3QhFEfwIStVko4fQ0NJ2VpqyVxOXiuGo3uOZF/f17Orwmo6rnmuOHIlt+BbB07YLl7jZXOHOLe3o+WNXDUjCGt8Jf8+zlgkFyRSS/+c+54Bk4Kv3Y5kqOjP/WPaSiVyCapCEgv8nc9vi2RViX26QDiJzJzcWYQv2XEB8jMUrYCyU5pGMRwAFoFRcdoIKVZTC+nDuO9Fri+OG8hYUJ5yYjFn0e+I8X0s2jmnRDudQrScS51JChux5H2A/QBVFYmcC8rmShHvWa0qwx20EfdFk1q64Q40oy3LbmtKGtNQFWQLernhR+145d0yR4ixznu7Aj56yiciG40drc2W0dssxtt5FjElmf3HzRzuBxExRUXPIQGZ+xpf6WtlHyTGLp295COUnYj0Ma/EvgJaspgahuRi6H2WnLv1DjrMT5O1wDB2eVOb8Ybfk3dreFSP1y7KChwlcAqTwBqq3ECoCtUWR6SYv1x2BVYd3fAZ+7MRm88gBSDqY0kIRMx/mu3IvXeHugQVnkrEyeHFz//2wij+KC040AH+NDuKFw=
  file: testfairy-intellij-$TRAVIS_TAG-bin.zip
  on:
    repo: testfairy/testfairy-android-studio-plugin
    all_branches: true
